models:
  chat_model:
    type: deepseek
    model: 'deepseek-chat'
    api_base: 'https://api.deepseek.com'
    api_key: $DEEPSEEK_API_KEY
    temperature: 0
    top_p: 1.0
    max_tokens: 8192
    timeout: 60
    max_retries: 3
    # type: doubao
    # model: 'doubao-seed-1-6-250615'
    # api_base: 'https://ark.cn-beijing.volces.com/api/v3'
    # api_key: $ARK_API_KEY
    # temperature: 0
    # top_p: 1.0
    # max_tokens: 8192
    # timeout: 60
    # max_retries: 3

tools:
  enabled:
    - edit
    - read
    - write
    - grep
    - ls
    - tree
    - bash
    - web_crawl
    - web_search
  configs:
    web_crawl:
      api_key: $FIRECRAWL_API_KEY
    web_search:
      api_key: $TAVILY_API_KEY
  mcp_servers:
    docs-langchain:
      transport: 'streamable_http'
      url: 'https://docs.langchain.com/mcp'
